export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';

export const GET_EVENTS = 'GET_EVENTS'
export const RECEIVE_EVENTS = 'RECIEVE_EVENTS'

export const GET_DASHBOARD = 'GET_DASHBOARD'
export const RECEIVE_DASHBOARD = 'RECEIVE_DASHBOARD'

export const GET_SPREAD = 'GET_SPREAD'
export const RECEIVE_SPREAD = 'RECEIVE_SPREAD'

export const SEND_BID = 'SEND_BID'
export const RECEIVE_BID = 'RECEIVE_BID'

export const SEND_OFFER = 'SEND_OFFER'
export const RECEIVE_OFFER = 'RECEIVE_OFFER'

export const DEPLOY_OFFER = 'DEPLOY_OFFER'
export const COMPLETE_OFFER = 'COMPLETE_OFFER'
export const CONFIRM_SEND_OFFER = 'CONFIRM_SEND_OFFER'
export const CONFIRM_ACK_OFFER = 'CONFIRM_ACK_OFFER'

export const DEPLOY_BID = 'DEPLOY_BID'
export const COMPLETE_BID = 'COMPLETE_BID'
export const CONFIRM_SEND_BID = 'CONFIRM_SEND_BID'
export const CONFIRM_ACK_BID = 'CONFIRM_ACK_BID'



export const PUSHER_KEY = 'af5ea2d104cb59800855';